### ISSUE TITLE
subscribing to messages...easy question, i know

### ISSUE THREAD

**Issue by wegunterjr-Dematic** [lovepark/o3d3xx-ros#10]
So, I am just trying out a couple of things and using an example that subscribes to a turtlesim Pose message.  I am wanting to replicate that with an o3d3xx message, but I may not be thinking of it correctly:

code snip:
```
#include <ros/ros.h>
#include <turtlesim/Pose.h>

#include <iomanip>  //for std::precision, std::fixed

// a callback function. Executed each time a new pose message arrives
void poseMessageReceived(const turtlesim::Pose& msg)
{
	ROS_INFO_STREAM(std::setprecision(2) << std::fixed
	  << " position =(" << msg.x << " ," << msg.y << ")"
	  << " direction =" << msg.theta );
}
```

I Wonder how to get access to the messages. Do I do something like this at the top of my cpp and then create a callback function that is looking for that message?
```#include <sensor_msg/Image.h>```
I have nothing to back that up, but just reaching...

**Comment by tpanzarella** [comment]
This is outside of the scope of this project. I suggest you take a look at the beginner ROS tutorials [here](http://wiki.ros.org/ROS/Tutorials) or seek out general help [here](http://answers.ros.org/).

Good luck.

**Comment by tpanzarella** [comment]
@wegunterjr-Dematic  As an FYI, you could look at the code for the [FileWriterNode](https://github.com/lovepark/o3d3xx-ros/blob/master/src/o3d3xx_file_writer_node.cpp) as a starting point for learning this stuff specific to the O3D3xx. I hope that gets you going.
