### ISSUE TITLE
camera config error

### ISSUE THREAD

**Issue by bsbc** [lovepark/o3d3xx-ros#12]
Using Goldeneye-C3_1.3.712.swu on a o3d303, we ran into some problems, maybe related to using the updated firmware.

Here is the process we followed:
Using Windows:
1) updated the firmware to Goldeneye-C3_1.3.712.swu with the VisionAssistant SW
2) created different applications (settings) using the VisionAssistant SW

Using Ubuntu 14.04:
3) launched the camera with the standard o3dxxx-ros launch process: ‘roslaunch o3d3xx camera.launch ip:=192.168.0.69’
4) verified that things work using rviz
5) dumped the settings using with ‘rosservice call ?/?/Dump > settings.json’
6) then tried to load the ‘settings.json’ file back to the device with ‘roslaunch o3d3xx config.launch infile:=settings.json’, which is the point where things started to go wrong, despite that the output of this process indicates that the configuration went through without an error:

The camera.launch process started timing out, and continues to do so after relaunching and power-cycling. Lost connection to the camera.

We had to go back to step 1 in order to recover this.

**Comment by tpanzarella** [comment]
A few things:

1. That version of the firmware has not yet been tested. Please see the software compatibility matrices on both the `o3d3xx-ros` and `libo3d3xx` github pages. Next week, I will be releasing version `0.2.0` of `libo3d3xx` which is compatible with IFM's `1.1.288` firmware.

2. When calling the ROS `Dump` service and redirecting the output to a file, realize that `rosservice` annotates the return data in that file, so, the file is not proper JSON. You should remove the `rosservice` markup and try again. OR, stop your ROS framegrabber and just use the `libo3d3xx` tools: `o3d3xx-dump` and `o3d3xx-conf` which will dump/load pure (non-annotated) JSON.

I re-emphasize, point 1 above. I have not even looked at that version of the firmware yet.

**Comment by bsbc** [comment]
On point 2. Yes, I did remove the annotations in the settings.json file -- Othewise the `roslaunch o3d3xx config.launch infile:=settings.json` the returns with an error.

On 1. Ok. Reverted to an older version of the firmware, so everything is working fine now. Will look for the update.

**Comment by tpanzarella** [comment]
New code will be released early next week. I'm hoping on Monday. All that is left is a little documentation. 

In the meantime, if you want to work in "unsupported mode", I just pushed out my dev branches to github. For `libo3d3xx` you can build the `dev-0.2.0` branch. For `o3d3xx-ros` you can build the `dev-0.1.7` branch. You can then flash your camera with the `1.1.288` firmware available [here](https://github.com/lovepark/libo3d3xx/tree/dev-0.2.0/firmware).

**Comment by tpanzarella** [comment]
@bsbc Thinking about your original post from above, the behavior you describe is symptomatic of loading up a camera configuration but not having an application marked as active. Two easy ways to check if that were the case: 1) `o3d3xx-dump` (or call the ROS `Dump` service), 2) `o3d3xx-ls`. In the second case, the active application will be marked with an asterisk -- if there is an active application.

Just a thought, if you really wanted to try again. However, the fact remains that I have not had the opportunity to look at the `1.3.x` firmware.

**Comment by bsbc** [comment]
Not having any of the applications marked active might have been a problem. I will double-check that.

For now, we are using Goldeneye-C3_1.1.288-288.swu firmware and updating the configuration (as described originally) works fine.

We will update the firmware once you'll have an official release. Thanks,
