### ISSUE TITLE
Cannot configure O3D303

### ISSUE THREAD

**Issue by zfxw0206** [lovepark/o3d3xx-ros#18]
When I want to use ROS to configure the O3D303 camera by using "roslaunch o3d3xx config.launch infile:=/home/administrator/wspace/src/o3d3xx/json/ex_camera2.json", I always get the message:
[ INFO] [1458240896.994179177]: status=-9014
[ INFO] [1458240896.994316742]: msg=XMLRPC value out of range

I also tried to use "rosservice call /o3d3xx/camera/Dump > /tmp/camera.json" to get the current setting, do nothing and run "roslaunch o3d3xx config.launch infile:=/tmp/camera.json" I will get the message:
[ INFO] [1458241148.110545217]: status=-1
[ INFO] [1458241148.110678292]: msg=<unspecified file>(1): expected object or array

Does anybody know how to fix it? Thank you!

**Comment by graugans** [comment]
Can you please provide the version of your firmware on the camera. For example dumped by ``3d3xx-dump``

**Comment by zfxw0206** [comment]
It is "O3D3xx FW 1.3.1001".

I tried to run o3d3xx-dump, but got the error:
Failed to dump camera configuration: 
XMLRPC call timed out

**Comment by tpanzarella** [comment]
A couple of things... First, as @graugans says, please make sure you are using a supported software stack. IFM firmware + libo3d3xx + o3d3xx-ros. The main README's for both libo3d3xx and o3d3xx-ros have software compatibility matrices that will allow you to trace to the proper stack.

Now for the specific issues...

> When I want to use ROS to configure the O3D303 camera by using "roslaunch o3d3xx config.launch infile:=/home/administrator/wspace/src/o3d3xx/json/ex_camera2.json", I always get the message:
> [ INFO] [1458240896.994179177]: status=-9014
> [ INFO] [1458240896.994316742]: msg=XMLRPC value out of range

Likely some value you are setting in the file exceeds a valid range. What did you change? I'd start there. Also, you can look at the `libo3d3xx` logs (they go to `/tmp` by default) to get more info.

> I also tried to use "rosservice call /o3d3xx/camera/Dump > /tmp/camera.json" to get the current setting, do nothing and run "roslaunch o3d3xx config.launch infile:=/tmp/camera.json" I will get the message:
> [ INFO] [1458241148.110545217]: status=-1
> [ INFO] [1458241148.110678292]: msg=(1): expected object or array

The output from `rosservice` is not valid json. The return values from the service call are annotated by the rosservice variable names. You either have to edit the file so it is actually valid JSON or just use the `libo3d3xx` equivalent command line tools to the rosservice calls. Those are `o3d3xx-config` and `o3d3xx-dump`.

> I tried to run o3d3xx-dump, but got the error:
> Failed to dump camera configuration: 
> XMLRPC call timed out

Sounds to me your network setup is odd. The XMLRPC timeouts are coming directly from `libcurl`. Is your routing table correct? Are you on a noisy network (e.g., Wifi)? Anything else non-standard or wierd we should be aware of when helping you troubleshoot this?

**Comment by zfxw0206** [comment]
Solved in [#47](https://github.com/lovepark/libo3d3xx/issues/47). Thank you!
