### ISSUE TITLE
Interpreting /cloud message

### ISSUE THREAD

**Issue by bibarz** [lovepark/o3d3xx-ros#19]
I'm working with @bsbc trying to use the pointcloud ROS message from the ifm camera and have a couple questions about it. Here is a sample of message  contents:

====================================================================
height: 132
width: 176
fields: 
  - 
    name: x
    offset: 0
    datatype: 7
    count: 1
  - 
    name: y
    offset: 4
    datatype: 7
    count: 1
  - 
    name: z
    offset: 8
    datatype: 7
    count: 1
  - 
    name: intensity
    offset: 16
    datatype: 7
    count: 1

is_bigendian: False

point_step: 32

row_step: 5632

data: [0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 128, 63, 0, 0, 22, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 128, 63, 0, 0, 30, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 128, 63, 0, 128, 35, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...

====================================================================

I show data for 3 points (96 bytes). My questions are:
- it seems there should be 32 bytes per pixel, so 132\*176\*32=743424 bytes, but the size of the message seems to be half of that, 371712
- according to the format, bytes 12-15 don't have meaning, and yet they are not zero, what do they mean? (in the example, they are all 0,0,128,63 which is float 1.0)
- 0,0,192,127 is float nan, so the three points shown above are invalid, I guess, but still they have different intensity values (if bytes 16-19 are indeed intensity; the float values above are 600.0, 632.0 and 654.0). Are these values meaningful?

Thanks for your help.

**Comment by tpanzarella** [comment]
> I show data for 3 points (96 bytes). My questions are:

OK. I validated this in an ipython shell, including unpacking each of the three points:

```
In [29]: data = np.array([0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 128, 63, 0, 0, 22, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 128, 63, 0, 0, 30, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 192, 127, 0, 0, 128, 63, 0, 128, 35, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.uint8)

In [30]: data.size
Out[30]: 96

In [31]: b1 = bytearray(data[0:32])

In [32]: struct.unpack("<ffffffff", b1)
Out[32]: (nan, nan, nan, 1.0, 600.0, 0.0, 0.0, 0.0)

In [33]: b2 = bytearray(data[32:64])

In [34]: struct.unpack("<ffffffff", b2)
Out[34]: (nan, nan, nan, 1.0, 632.0, 0.0, 0.0, 0.0)

In [35]: b3 = bytearray(data[64:96])

In [36]: struct.unpack("<ffffffff", b3)
Out[36]: (nan, nan, nan, 1.0, 654.0, 0.0, 0.0, 0.0)
```
You'll note that each point contains 8 floats (x, y, z, PAD, intensity, PAD, PAD, PAD). For refrence, the `pcl::Point<XYZI>` structure looks like:

```
union
{
  float data[4];
  struct
  {
    float x;
    float y;
    float z;
  };
};
union
{
  struct
  {
    float intensity;
  };
  float data_c[4];
};
```
The PAD floats are there to facilitate SSE alignment so various operations can be vectorized. Quoting the PCL docs:

> Simple XYZ + intensity point type. In an ideal world, these 4 components would create a single structure, SSE-aligned. However, because the majority of point operations will either set the last component of the data[4] array (from the xyz union) to 0 or 1 (for transformations), we cannot make intensity a member of the same structure, as its contents will be overwritten. For example, a dot product between two points will set their 4th component to 0, otherwise the dot product doesn’t make sense, etc.
Therefore for SSE-alignment, we pad intensity with 3 extra floats. Inefficient in terms of storage, but good in terms of memory alignment.

OK. The above being background, let's get back to your points above.

> it seems there should be 32 bytes per pixel, so 132*176*32=743424 bytes, but the size of the message seems to be half of that, 371712

I validated this on my machine by writing the output of `rostopic echo ...` to a file then reading the data bytes into numpy. (In my example below, I also unpack the first point just to show it has the expected structure of the XYZI point type as your data are showing above as well):

```
In [37]: a = np.loadtxt('/tmp/cloud.csv', delimiter=',', dtype=np.uint8)

In [38]: a.size
Out[38]: 743424

In [39]: b = bytearray(a[0:32])

In [40]: struct.unpack("<ffffffff", b)
Out[40]: 
(0.6129999756813049,
 0.38199999928474426,
 0.29600000381469727,
 1.0,
 741.0,
 0.0,
 0.0,
 0.0)
```
As you can see, I am getting all 743424 bytes. How to you get to the 371712? Now, given the above background information regarding the pad bytes for SSE alignment, we know that only half of the data are actually "good" data, the rest are padding. So, maybe that is where your number is coming from. However, I still would like to know where you got the 371712 number as on my machine, all 743424 are being sent over the ROS message.



> according to the format, bytes 12-15 don't have meaning, and yet they are not zero, what do they mean? (in the example, they are all 0,0,128,63 which is float 1.0)

I think my above quote from the PCL docs answer this one.



> 0,0,192,127 is float nan, so the three points shown above are invalid, I guess, but still they have different intensity values (if bytes 16-19 are indeed intensity; the float values above are 600.0, 632.0 and 654.0). Are these values meaningful?

Yes. The `nan` are explicitly placed into the point cloud by the `libo3d3xx` driver as it is receiving bytes off the wire from the camera. This is determined by consulting the "good/bad bit" in the corresponding point in the confidence image. Regardless of whether or not the point was detected as bad and encoded as `nan`, I am still copying into the cloud the corresponding value from the amplitude image. So, yes, the amplitude value is meaningful in the sense that it is in fact the *normalized* amplitude value that is reported back by the camera. There are reasons, other than a low amplitude threshold, that a pixel can be flagged as bad.

I am not sure if I have answered all of your questions here, but, hopefully some of the above helps.

**Comment by bibarz** [comment]
Thanks, that does answer my questions. The reason I was getting half the expected message size was that I counted it from a processed topic by mistake.
