### ISSUE TITLE
install issues test errors

### ISSUE THREAD

**Issue by sjorsjee** [lovepark/o3d3xx-ros#27]
Hello,

I'm having issues installing this Ros package.
I installed the libo3d3xx version0.4.5 and use Ros Indigo.
I use the newest version of this ros package.

It always fails at the catkin_make run_tests

sjors@sjors-VirtualBox:~/dev/o3d3xx-catkin$ catkin_make -DCATKIN_ENABLE_TESTING=ON
Base path: /home/sjors/dev/o3d3xx-catkin
Source space: /home/sjors/dev/o3d3xx-catkin/src
Build space: /home/sjors/dev/o3d3xx-catkin/build
Devel space: /home/sjors/dev/o3d3xx-catkin/devel
Install space: /home/sjors/dev/o3d3xx-catkin/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/sjors/dev/o3d3xx-catkin/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/sjors/dev/o3d3xx-catkin/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - o3d3xx
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'o3d3xx'
-- ==> add_subdirectory(o3d3xx)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
-- Using these message generators: gencpp;genlisp;genpy
-- o3d3xx: 1 messages, 5 services
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sjors/dev/o3d3xx-catkin/build
####
####
[  0%] Built target _o3d3xx_generate_messages_check_deps_Rm
[  0%] Built target _o3d3xx_generate_messages_check_deps_Config
[  0%] Built target _o3d3xx_generate_messages_check_deps_Dump
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target _o3d3xx_generate_messages_check_deps_Extrinsics
[  0%] Built target _o3d3xx_generate_messages_check_deps_GetVersion
[  0%] Built target _o3d3xx_generate_messages_check_deps_Trigger
[ 27%] Built target o3d3xx_generate_messages_cpp
[ 31%] Built target o3d3xx_config_node
[ 31%] Built target std_msgs_generate_messages_lisp
[ 59%] Built target o3d3xx_generate_messages_lisp
[ 59%] Built target std_msgs_generate_messages_py
[ 95%] Built target o3d3xx_generate_messages_py
[ 95%] Built target o3d3xx_generate_messages
[100%] Built target o3d3xx_node
sjors@sjors-VirtualBox:~/dev/o3d3xx-catkin$ catkin_make run_tests
Base path: /home/sjors/dev/o3d3xx-catkin
Source space: /home/sjors/dev/o3d3xx-catkin/src
Build space: /home/sjors/dev/o3d3xx-catkin/build
Devel space: /home/sjors/dev/o3d3xx-catkin/devel
Install space: /home/sjors/dev/o3d3xx-catkin/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/sjors/dev/o3d3xx-catkin/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/sjors/dev/o3d3xx-catkin/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - o3d3xx
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'o3d3xx'
-- ==> add_subdirectory(o3d3xx)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
-- Using these message generators: gencpp;genlisp;genpy
-- o3d3xx: 1 messages, 5 services
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sjors/dev/o3d3xx-catkin/build
####
####
Removing test result files from '/home/sjors/dev/o3d3xx-catkin/build/test_results/o3d3xx'
- removing '/home/sjors/dev/o3d3xx-catkin/build/test_results/o3d3xx/nosetests-test.xml'
- removing '/home/sjors/dev/o3d3xx-catkin/build/test_results/o3d3xx/rosunit-test_camera.xml'
- removing '/home/sjors/dev/o3d3xx-catkin/build/test_results/o3d3xx/rostest-test_o3d3xx.xml'
- removing '/home/sjors/dev/o3d3xx-catkin/build/test_results/o3d3xx/rosunit-test_services.xml'
Built target clean_test_results_o3d3xx
Built target tests
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/sjors/dev/o3d3xx-catkin/src/o3d3xx --package=o3d3xx --results-filename test_o3d3xx.xml --results-base-dir /home/sjors/dev/o3d3xx-catkin/build/test_results /home/sjors/dev/o3d3xx-catkin/src/o3d3xx/test/o3d3xx.test 
... logging to /home/sjors/.ros/log/rostest-sjors-VirtualBox-18103.log
[ROSUNIT] Outputting test results to /home/sjors/dev/o3d3xx-catkin/build/test_results/o3d3xx/rostest-test_o3d3xx.xml
terminate called after throwing an instance of 'o3d3xx::error_t'
  what():  XMLRPC call timed out
terminate called after throwing an instance of 'o3d3xx::error_t'
  what():  XMLRPC call timed out
Traceback (most recent call last):
  File "/home/sjors/dev/o3d3xx-catkin/src/o3d3xx/test/test_services.py", line 66, in <module>
    sys.exit(main())
  File "/home/sjors/dev/o3d3xx-catkin/src/o3d3xx/test/test_services.py", line 62, in main
    rostest.rosrun('o3d3xx', 'test_services', TestServices, sys.argv)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 145, in rosrun
    result = rosunit.create_xml_runner(package, test_name, result_file).run(suite)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 233, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 395, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/sjors/dev/o3d3xx-catkin/src/o3d3xx/test/test_services.py", line 18, in test_services
    rospy.wait_for_service("/Dump")
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 159, in wait_for_service
    raise ROSInterruptException("rospy shutdown")
rospy.exceptions.ROSInterruptException: rospy shutdown
testtest_camera ... ok
testtest_services ... ERROR!
ERROR: max time [60.0s] allotted for test [test_services] of type [o3d3xx/test_services.py]
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 681, in run_test
    (test.time_limit, test.test_name, test.package, test.type))
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

[o3d3xx.rosunit-test_camera/test_camera][FAILURE]-------------------------------
False is not true
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/sjors/dev/o3d3xx-catkin/src/o3d3xx/test/test_camera.py", line 82, in test_camera
    self.assertTrue(self.success)
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 1
 * FAILURES: 1

rostest log file is in /home/sjors/.ros/log/rostest-sjors-VirtualBox-18103.log
-- run_tests.py: verify result "/home/sjors/dev/o3d3xx-catkin/build/test_results/o3d3xx/rostest-test_o3d3xx.xml"
Built target _run_tests_o3d3xx_rostest_test_o3d3xx.test
Built target _run_tests_o3d3xx_rostest
-- run_tests.py: execute commands
  /usr/bin/cmake -E make_directory /home/sjors/dev/o3d3xx-catkin/build/test_results/o3d3xx
  /usr/bin/nosetests-2.7 -P --process-timeout=60 --where=/home/sjors/dev/o3d3xx-catkin/src/o3d3xx/test --with-xunit --xunit-file=/home/sjors/dev/o3d3xx-catkin/build/test_results/o3d3xx/nosetests-test.xml

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
-- run_tests.py: verify result "/home/sjors/dev/o3d3xx-catkin/build/test_results/o3d3xx/nosetests-test.xml"
Built target _run_tests_o3d3xx_nosetests_test
Built target _run_tests_o3d3xx_nosetests
Built target _run_tests_o3d3xx
Built target run_tests

**Comment by tpanzarella** [comment]
Are you running the tests with your camera connected and turned on? It
looks like the test errored because libo3d3xx threw an exception as a
result of an XMLRPC call to the camera timing out. Typically indicative of
a connection problem to the camera. I also notice you are running in
Virtual Box ... make sure there are no networking issues going on.

--
Tom Panzarella
(sent from my phone)

**Comment by sjorsjee** [comment]
Yes the camera is turned on.
When we installed libo3d3xx the virtual-box made no difference.
We are using a switch so the camera has an other IP. 192.168.125.10.
I don know if this can be the problem

**Comment by tpanzarella** [comment]
Yep. That is likely the issue. Unit tests assume the default IP. You should
be able to set the environment variable O3D3XX_IP=192.168.125.10 and make
it work, otherwise you may have to pass the IP to the launch file.
Basically, your error is one of connectivity.

--
Tom Panzarella
(sent from my phone)

**Comment by sjorsjee** [comment]
We had to chance the IP in the launch file.
just setting the environment variable didn't work.
Thank you very much for your help !!!

**Comment by tpanzarella** [comment]
Yeah, I figured that would be the case. The launch file explicitly passes
an IP to the Camera ctor which overrides the environment variable. When
running outside the unit test you can pass the IP as an arg to the launch
file.

--
Tom Panzarella
(sent from my phone)
