### ISSUE TITLE
only half of the information from zyx_image

### ISSUE THREAD

**Issue by sjorsjee** [lovepark/o3d3xx-ros#29]
Hello,

We are using the xyz_image (topic) to determine the x,y,z value of a pixel. When we read of this topic it looks like we only get half of the information. because it is a 16-bit value but we get two times an 8-bit. if we combine those 8-bits we get the correct distance. but by using this way we only get half of the pixels. 

are we doing something wrong or is this normal? 
I hope someone can help.

// ROS
#include <ros/ros.h>
#include <geometry_msgs/Twist.h> 
#include <stdlib.h> 
#include <std_msgs/String.h> 

// OpenCV
#include <image_transport/image_transport.h>
#include <cv_bridge/cv_bridge.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/image_encodings.h>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>

using namespace cv;
namespace enc = sensor_msgs::image_encodings;

// Read message
void read_image(const sensor_msgs::ImagePtr& msg)
{
	// Read image
	cv_bridge::CvImagePtr img_ptr;

 	try
    	{
      		img_ptr = cv_bridge::toCvCopy(msg, enc::TYPE_16SC3);
    	}
   	catch (cv_bridge::Exception& e)
    	{
      		ROS_ERROR("cv_bridge exception: %s", e.what());
      		return;
    	}
	
	// Split channels
	Mat channels[3];
	split(img_ptr->image, channels);

	// Create mat objects for calcuations
	Mat img_z = Mat(channels[0].rows, channels[0].cols, CV_16SC1);
	Mat img_x = Mat(channels[1].rows, channels[1].cols, CV_16SC1);
	Mat img_y = Mat(channels[2].rows, channels[2].cols, CV_16SC1);
	
	// z-as matrix maken
	for (int row = 0; row < channels[0].rows; row++)
	{	
		for (int col = 0; col < channels[0].cols*2; col = col+2)
		{
			int8_t val0 = channels[0].at<uchar>(row, col);
			int8_t val1 = channels[0].at<uchar>(row, col+1);
			int16_t result = (val1 << 8 | val0);			
			img_z.at<uchar>(row, col/2) = result;	
		}
	
	}
	// x-as matrix maken
	for (int row = 0; row < channels[1].rows; row++)
	{
		for (int col = 0; col < channels[1].cols*2; col = col+2)
		{
			int8_t val0 = channels[1].at<uchar>(row, col);
			int8_t val1 = channels[1].at<uchar>(row, col+1);
			int16_t result = (val1 << 8 | val0);			
			img_x.at<uchar>(row, col/2) = result;	
			
		}
	
	}
	// y-as matrix maken
	for (int row = 0; row < channels[2].rows; row++)
	{
		for (int col = 0; col < channels[2].cols*2; col = col+2)
		{
			int8_t val0 = channels[2].at<uchar>(row, col);
			int8_t val1 = channels[2].at<uchar>(row, col+1);
			int16_t result = (val1 << 8 | val0);			
			img_y.at<uchar>(row, col/2) = result;	
		}
	
	}

	// foto z
	namedWindow("img_z", CV_WINDOW_AUTOSIZE);
	imshow("img_z", img_z);
	waitKey(1);
	
}

// Start and initialize the node
int main(int argc, char **argv) 
{
	// Initialize ros node
	ros::init(argc, argv, "listener");
	ros::NodeHandle nh;
	
	// Subscribe to the topic
	ros::Subscriber sub = nh.subscribe("o3d3xx/camera/xyz_image", 100, read_image);

	// Wait for messages
	ros::spin();
}

**Comment by tpanzarella** [comment]
To do what you want, you just need to do something like:

```
cv::Mat xim, yim, zim;
std::vector<cv::Mat> channels(3);
cv::split(xyz, channels);

xim = channels[0];
yim = channels[1];
zim = channels[2];
```

Now each individual spatial plane of the image is available as a single channel image with the same number of rows, columns, and pixel depth (namely signed 16-bit integers) as the original 3-channel image.

Now, what I am suggesting above is what you should do. However, to answer one of your concerns above:

> but by using this way we only get half of the pixels.

This is a result of (using your z-image plane as an example):

```
img_z.at<uchar>(row, col/2) = result;
```

The pixel depth is 16-bits not 8.

But again, your code is over complicating things. Use the above snippet I have posted in and you should be good to go.

**Comment by sjorsjee** [comment]
Thanks for your reaction.

if i understand you correctly i can use it this way. 
i stil get the wrong numbers. can it be that the image is being converted wrong from the topic ? 

sorry for bothering you

// ROS
#include <ros/ros.h>
#include <geometry_msgs/Twist.h> 
#include <stdlib.h> 
#include <std_msgs/String.h> 

// OpenCV
#include <image_transport/image_transport.h>
#include <cv_bridge/cv_bridge.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/image_encodings.h>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>

using namespace cv;
namespace enc = sensor_msgs::image_encodings;

// Read message
void read_image(const sensor_msgs::ImagePtr& msg)
{
	// Read image
	cv_bridge::CvImagePtr img_ptr;

 	try
    	{
      		img_ptr = cv_bridge::toCvCopy(msg, enc::TYPE_16SC3);
    	}
   	catch (cv_bridge::Exception& e)
    	{
      		ROS_ERROR("cv_bridge exception: %s", e.what());
      		return;
    	}
		cv::Mat xim, yim, zim;
		std::vector<cv::Mat> channels(3);
		cv::split(img_ptr->image, channels);

		xim = channels[0];
		yim = channels[1];
		zim = channels[2];
	
ROS_INFO("img %i",zim.at<char>(89,34));
	
}

// Start and initialize the node
int main(int argc, char **argv) 
{
	// Initialize ros node
	ros::init(argc, argv, "listener");
	ros::NodeHandle nh;
	
	// Subscribe to the topic
	ros::Subscriber sub = nh.subscribe("o3d3xx/camera/xyz_image", 100, read_image);

	// Wait for messages
	ros::spin();
}

**Comment by tpanzarella** [comment]
Two things:

First, you should change:

```
zim.at(89,34)
```

to

```
zim.at<std::int16_t>(89,34)
```

Second, be aware that the `xyz_image` is in the same coordinate frame as the point cloud, namely x-forward, y-left, z-up. The only difference is that the data are sent as signed 16-bit ints in mm rather than 32-bit floats in meters as the point cloud does.

**Comment by sjorsjee** [comment]
Thank you!
That was the problem.
I think it is fixed now.
