### ISSUE TITLE
using mask to lower the amount of information to pc 

### ISSUE THREAD

**Issue by sjorsjee** [lovepark/o3d3xx-ros#30]
Hey,
I hoop someone can help me. 
I'm trying to lower the amount of information to the pc by using a mask/schema.
(https://github.com/lovepark/libo3d3xx/blob/master/doc/utils.md#o3d3xx-schema).
but to be honest I dont know how to chances the mask.
What do i have to chance for an other mask?

I hoop someone can help me.

**Comment by sjorsjee** [comment]
I found out how to use the mask. So that is not a problem any more.
But it still gets to much information. 
We want to turn the camera on and of with a trigger. 
Can you help me with this ?

**Comment by tpanzarella** [comment]
Assuming the application you want to edit on the camera is located at index 1 (you can get this information with `o3d3xx-ls`), to software trigger the camera you can:

```
$ echo '{"o3d3xx":{"Apps":[{"TriggerMode":"2","Index":"1"}]}}' | o3d3xx-config
```

Of course, you now have to explicitly trigger the camera in order to acquire new pixel data. If you want to go back to free running mode:

```
echo '{"o3d3xx":{"Apps":[{"TriggerMode":"1","Index":"1"}]}}' | o3d3xx-config
```

If you want to hardware trigger the camera, I refer you to [this thread](https://github.com/lovepark/libo3d3xx/issues/46)

**Comment by sjorsjee** [comment]
Thank you for your reaction.

If I use that command I get an error. 

sjors@sjors-VirtualBox:~$ echo '{"o3d3xx":{"Apps":[{"TriggerMode":"2","Index":"1"}]}}' | o3d3xx-config
Failed to configure camera from JSON config '-':
XMLRPC call timed out

don know if im doing something wrong ?

**Comment by graugans** [comment]
Does your sensor have an IP which is different from the default one (``192.168.0.69``)?

**Comment by sjorsjee** [comment]
Yes it is different. but we changed it in camera.launch to the IP we use. 
We use v0.4.5  of the O3d3xx and v0.2.5 from the ros package.
I dont know if that can be te problem.

**Comment by tpanzarella** [comment]
The `o3d3xx-config` tool operates outside of the ROS environment. And, so, it follows that you would need to specify the IP Address to `o3d3xx-config` explicitly via the `--ip` command line argument or implicitly via the `O3D3XX_IP` environment variable. Alternately, to do the equivalent while staying within ROS, assuming your camera node is up and running, connected to the camera, etc., you can:

```
$ echo '{"o3d3xx":{"Apps":[{"TriggerMode":"1","Index":"1"}]}}' | roslaunch o3d3xx config.launch
```

**Comment by sjorsjee** [comment]
Thank you.
I can chance the triggermode now. 
So now i only have to send information on the  "/o3d3xx/camera/Trigger" service right ?

**Comment by tpanzarella** [comment]
Assuming you set the camera to software trigger, calling the service you
mention will trigger an image acquisition. Pixel data are received on the
usual topics, asynchronously.

--
Tom Panzarella
(sent from my phone)

**Comment by sjorsjee** [comment]
thank you.
everyting is working now
