### ISSUE TITLE
Problem with nodes while launching ros

### ISSUE THREAD

**Issue by RamonGomez** [lovepark/o3d3xx-ros#35]
Hello, im receiving this while trying to launch the camera module:

root@ramon-VirtualBox:/home/ramon# roslaunch /home/ramon/proyecto_camara/o3d3xx-ros/launch/camera.launch ip:=192.168.1.73
... logging to /root/.ros/log/d14f125c-04ba-11e7-821b-0800272f682b/roslaunch-ramon-VirtualBox-7512.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ramon-VirtualBox:44047/

SUMMARY
========

PARAMETERS
 * /o3d3xx/camera/assume_sw_triggered: False
 * /o3d3xx/camera/frame_id_base: o3d3xx/camera
 * /o3d3xx/camera/ip: 192.168.1.73
 * /o3d3xx/camera/password: 
 * /o3d3xx/camera/publish_viz_images: True
 * /o3d3xx/camera/schema_mask: 15
 * /o3d3xx/camera/timeout_millis: 500
 * /o3d3xx/camera/timeout_tolerance_secs: 5.0
 * /o3d3xx/camera/xmlrpc_port: 80
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /o3d3xx/
    camera (o3d3xx/o3d3xx_node)
    camera_tf (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
ERROR: cannot launch node of type [o3d3xx/o3d3xx_node]: o3d3xx
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share
process[o3d3xx/camera_tf-2]: started with pid [7530]

## And this one with the rviz.launch:

root@ramon-VirtualBox:/home/ramon# roslaunch /home/ramon/proyecto_camara/o3d3xx-ros/launch/camera.launch ip:=192.168.1.73
... logging to /root/.ros/log/d14f125c-04ba-11e7-821b-0800272f682b/roslaunch-ramon-VirtualBox-7512.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ramon-VirtualBox:44047/

SUMMARY
========

PARAMETERS
 * /o3d3xx/camera/assume_sw_triggered: False
 * /o3d3xx/camera/frame_id_base: o3d3xx/camera
 * /o3d3xx/camera/ip: 192.168.1.73
 * /o3d3xx/camera/password: 
 * /o3d3xx/camera/publish_viz_images: True
 * /o3d3xx/camera/schema_mask: 15
 * /o3d3xx/camera/timeout_millis: 500
 * /o3d3xx/camera/timeout_tolerance_secs: 5.0
 * /o3d3xx/camera/xmlrpc_port: 80
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /o3d3xx/
    camera (o3d3xx/o3d3xx_node)
    camera_tf (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
ERROR: cannot launch node of type [o3d3xx/o3d3xx_node]: o3d3xx
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share
process[o3d3xx/camera_tf-2]: started with pid [7530]

Looks like ros problem. Any idea?

Greetings and thanks,
Juan Ramón Gómez Martín.

**Comment by tpanzarella** [comment]
You need to make sure that the `o3d3xx` package is integrated with your ROS install. For example, if you cannot: `$ roscd o3d3xx` and land in the package directory, your setup is incorrect. See the notes [here](https://github.com/lovepark/o3d3xx-ros#building-and-installing-the-software) regarding a little snippet you can put in your `~/.bash_profile` or `~/.bashrc` depending upon how you have your login scripts setup for your shell.

**Comment by RamonGomez** [comment]
Just a thing: I'm using ROS Kinetic. Should i replace the folder with Kinetic instead of Indigo?

**Comment by tpanzarella** [comment]
Sure. The docs reflect what I was using at the time. Indeed, it is just there for exemplary purposes. Kinetic is fine / preferred.

**Comment by RamonGomez** [comment]
Working now, thanks.
