### ISSUE TITLE
Doubt on the dataframe

### ISSUE THREAD

**Issue by RamonGomez** [lovepark/o3d3xx-ros#37]
Hello again,

We have a doubt about the frame we get through this lib: In the PCL file (through ex-file_io), we obtain 4 data per point. No problem with the first 3 points (coordinates of the point), but what about the last point, the intensity? Is it tied to one of the coordinates (x or y) or to the IR reflection?

By the way, the dataframe we get, in what order is displayed? From left to right and from top to bottom?

Thanks,
Juan Ramón Gómez Martín.

**Comment by tpanzarella** [comment]
> We have a doubt about the frame we get through this lib: In the PCL file (through ex-file_io), we obtain 4 data per point. No problem with the first 3 points (coordinates of the point), but what about the last point, the intensity? Is it tied to one of the coordinates (x or y) or to the IR reflection?

The sensor does not return intensity information it returns amplitude, both raw and normalized. We populate the intensity channel of each of the `pcl::PointXYZI` data structures to be the normalized amplitude registered to the particular pixel in question. These are the same data that are returned in the `AmplitudeImage()` just packaged together with the point cloud data for convenience.

> By the way, the dataframe we get, in what order is displayed? From left to right and from top to bottom?

At time of construction the data are populated as an MxN array where M and N depend upon your imager  resolution. The data are populated in row-major order. In terms of the PCL serialization order to the PCD file, you can ask the PCL developers that question. However, you can also discover the answer yourself with very minimal effort and so I'll leave that as an exercise for you to do.

Hopefully this helps.

**Comment by RamonGomez** [comment]
It helped. Lot of thanks.

Juan Ramón Gómez.
